//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDatabaseApplication.Models
{
    using System.Data.Entity;

    public partial class BookDatabaseEntities1 : DbContext
    {

        public BookDatabaseEntities1()
            : base("name=BookDatabaseEntities1")
        {
            Database.SetInitializer(new DropCreateDatabaseIfModelChanges<BookDatabaseEntities1>());
        }

        public virtual DbSet<Table> Tables { get; set; }
    }
}
